"""作业核心模型与作业管理

Revision ID: 14cbab704b41
Revises:
Create Date: 2026-10-08 17:38:07.295033

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14cbab704b41"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("subject", sa.String(length=100), nullable=False),
        sa.Column("grade_level", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('draft', 'published')", name="ck_assignments_status"),
        sa.CheckConstraint(
            "length(trim(grade_level)) > 0", name="ck_assignments_grade_level_not_blank"
        ),
        sa.CheckConstraint("length(trim(subject)) > 0", name="ck_assignments_subject_not_blank"),
        sa.CheckConstraint("length(trim(title)) > 0", name="ck_assignments_title_not_blank"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_assignments_status_created_at", "assignments", ["status", "created_at"], unique=False
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("question_number", sa.Integer(), nullable=False),
        sa.Column("question_type", sa.String(length=30), nullable=False),
        sa.Column("stem", sa.Text(), nullable=False),
        sa.Column("max_score", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "question_type IN ('single_choice', 'multiple_choice', 'fill_blank', "
            "'short_answer', 'essay')",
            name="ck_questions_type",
        ),
        sa.CheckConstraint("length(trim(stem)) > 0", name="ck_questions_stem_not_blank"),
        sa.CheckConstraint("max_score > 0", name="ck_questions_max_score_positive"),
        sa.CheckConstraint("question_number > 0", name="ck_questions_number_positive"),
        sa.ForeignKeyConstraint(["assignment_id"], ["assignments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "assignment_id", "question_number", name="uq_questions_assignment_number"
        ),
    )
    op.create_index("ix_questions_assignment_id", "questions", ["assignment_id"], unique=False)
    op.create_table(
        "answer_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("answer_content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=30), server_default="teacher", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('teacher', 'model_generated')", name="ck_answer_keys_source"
        ),
        sa.CheckConstraint("length(trim(answer_content)) > 0", name="ck_answer_keys_content"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_id", name="uq_answer_keys_question_id"),
    )
    op.create_table(
        "rubric_criteria",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("points", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("length(trim(description)) > 0", name="ck_rubric_criteria_description"),
        sa.CheckConstraint("points > 0", name="ck_rubric_criteria_points_positive"),
        sa.CheckConstraint("sort_order > 0", name="ck_rubric_criteria_order_positive"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_id", "sort_order", name="uq_rubric_criteria_question_order"),
    )
    op.create_index(
        "ix_rubric_criteria_question_id", "rubric_criteria", ["question_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rubric_criteria_question_id", table_name="rubric_criteria")
    op.drop_table("rubric_criteria")
    op.drop_table("answer_keys")
    op.drop_index("ix_questions_assignment_id", table_name="questions")
    op.drop_table("questions")
    op.drop_index("ix_assignments_status_created_at", table_name="assignments")
    op.drop_table("assignments")
    # ### end Alembic commands ###
