"""新增Canonical文档索引

Revision ID: f10c92b373a6
Revises: 339018f72219
Create Date: 2026-10-09 15:48:33.742442

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f10c92b373a6"
down_revision: Union[str, Sequence[str], None] = "339018f72219"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canonical_artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parsed_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("bucket", sa.String(length=63), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("normalizer_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("canonical_object_key", sa.String(length=1024), nullable=True),
        sa.Column("canonical_sha256", sa.String(length=64), nullable=True),
        sa.Column("canonical_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("block_count", sa.Integer(), nullable=True),
        sa.Column("source_parser", sa.String(length=32), nullable=False),
        sa.Column("source_parser_version", sa.String(length=64), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'available' AND canonical_object_key IS NOT NULL "
            "AND length(trim(canonical_object_key)) > 0 AND length(canonical_sha256) = 64 "
            "AND canonical_size_bytes >= 0 AND page_count > 0 AND block_count >= 0 "
            "AND failure_code IS NULL) OR "
            "(status = 'failed' AND canonical_object_key IS NULL "
            "AND canonical_sha256 IS NULL AND canonical_size_bytes IS NULL "
            "AND page_count IS NULL AND block_count IS NULL AND failure_code IS NOT NULL)",
            name="ck_canonical_artifacts_result_shape",
        ),
        sa.CheckConstraint(
            "status IN ('available', 'failed')", name="ck_canonical_artifacts_status"
        ),
        sa.CheckConstraint(
            "length(trim(bucket)) > 0 AND length(trim(normalizer_version)) > 0",
            name="ck_canonical_artifacts_storage_and_version",
        ),
        sa.ForeignKeyConstraint(
            ["parsed_artifact_id"], ["parsed_artifacts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parsed_artifact_id",
            "normalizer_version",
            name="uq_canonical_artifacts_source_normalizer",
        ),
    )
    op.create_index(
        "ix_canonical_artifacts_submission_created_at",
        "canonical_artifacts",
        ["submission_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_canonical_artifacts_submission_created_at", table_name="canonical_artifacts")
    op.drop_table("canonical_artifacts")
    # ### end Alembic commands ###
