"""学生作业提交与原始文件存储

Revision ID: fd1e8d651902
Revises: 14cbab704b41
Create Date: 2026-10-08 19:02:11.507422

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd1e8d651902"
down_revision: Union[str, Sequence[str], None] = "14cbab704b41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("student_ref", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="submitted", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status = 'submitted'", name="ck_submissions_status"),
        sa.CheckConstraint("length(trim(student_ref)) > 0", name="ck_submissions_student_ref"),
        sa.ForeignKeyConstraint(["assignment_id"], ["assignments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "assignment_id", "student_ref", name="uq_submissions_assignment_student_ref"
        ),
    )
    op.create_index(
        "ix_submissions_assignment_created_at",
        "submissions",
        ["assignment_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "parsing_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status = 'pending'", name="ck_parsing_tasks_status"),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id", name="uq_parsing_tasks_submission_id"),
    )
    op.create_index(
        "ix_parsing_tasks_status_created_at",
        "parsing_tasks",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "submission_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("bucket", sa.String(length=63), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_type IN ('application/pdf', 'image/jpeg', 'image/png')",
            name="ck_submission_files_content_type",
        ),
        sa.CheckConstraint("length(sha256) = 64", name="ck_submission_files_sha256_length"),
        sa.CheckConstraint("length(trim(bucket)) > 0", name="ck_submission_files_bucket"),
        sa.CheckConstraint("length(trim(object_key)) > 0", name="ck_submission_files_object_key"),
        sa.CheckConstraint(
            "length(trim(original_filename)) > 0", name="ck_submission_files_filename"
        ),
        sa.CheckConstraint("size_bytes > 0", name="ck_submission_files_size_positive"),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bucket", "object_key", name="uq_submission_files_bucket_object_key"),
        sa.UniqueConstraint("submission_id", name="uq_submission_files_submission_id"),
    )
    op.create_index(
        "ix_submission_files_created_at", "submission_files", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_submission_files_created_at", table_name="submission_files")
    op.drop_table("submission_files")
    op.drop_index("ix_parsing_tasks_status_created_at", table_name="parsing_tasks")
    op.drop_table("parsing_tasks")
    op.drop_index("ix_submissions_assignment_created_at", table_name="submissions")
    op.drop_table("submissions")
    # ### end Alembic commands ###
